# Site settings
title:       Unicorns and Magical Powders and Things.
email:       benzhangniu@gmail.com
author:      Ben Zhang
description: "My personal blog about anything majestic."
keywords: "HTML, CSS, Javascript, OpenSCAD, NodeJS, PHP"
baseurl:     "/~ctzhang/ben-z.github.io/"
url:         "https://www.student.cs.uwaterloo.ca/~ctzhang/ben-z.github.io"

# Google analytics - Replaced by CloudFlare
google_analytics: #UA-61801419-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: benzhang

# Social icons
show_social_icons: true
github_username: ben-z
stackoverflow_id: 4527337
twitter_username: un1c0rnioz
google_plus_id:
linkedin_username: benjaminz
bitcoin_url:
paypal_url:
flattr_button:
cv: assets/CV-web.pdf

# Post sharing icons
show_sharing_icons: true
share_text: 'Spread the word'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
  sass_dir: _sass
destination: ../../public_html/ben-z.github.io

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Rake settings
post:
  template: "post.txt"
  extension: md
git:
  branch: master
